# INF 8215 - Intelligence artif.: méthodes et algorithmes 
## Automne 2018 - TP3 - Machine Learning

**Date de rendu: 6 Décembre**

**Fichiers à rendre:**
    * TP3_FR.ipynb complété
    * SoftmaxClassifier.py complété
    * test_prediction.csv le fichier de résultat

## Introduction

Le but de ce TP est de vous donner un aperçu du déroulement général d'un projet de machine learning tout en vous familiarisant avec des librairies python adaptées.


Dans la première partie, vous implémenterez un algorithme de classification multiclasse appelé **softmax regression** à l'aide uniquement de la bibliothèque **numpy** et l'intégrerez à la bibliothèque **scikit-learn**.

Dans la deuxième partie, vous prendrez connaissance du **dataset** utilisé pour ce projet. Et vous serez amenés à effectuer le **preprocessing** de ces données pour qu'elles soient utilisables dans les algorithmes de machine learning classiques. Vous utiliserez les bibliothèques **pandas** et **scikit-learn**.

Enfin, dans la troisième partie, vous comparerez l'efficacité du modèle que vous avez implémenté avec d'autres modèles déjà implémentés dans **sklearn**. Puis vous tenterez d'améliorer les performances de l'algorithme sélectionné.

Pour enfin soumettre vos résultats sur la plateforme **kaggle**.

## Installation

Pour installer **pandas** et **scikit-learn** le plus simple est de télécharger et d'installer **Anaconda** qui regroupe les packages les plus utilisés pour le calcul scientifique et la science des données.

Vous trouverez la distribution ici : https://www.anaconda.com/download/#linux .

Assurez-vous d'avoir la version **20.0** de **scikit-learn**.

## Bonus 1: Compétition (2 points)

Quand vous aurez terminé le TP, vous pourrez soumettre vos prédictions sur **kaggle**, vous obtiendrez votre performance en terme de **log loss**.
Vous pouvez ensuite me communiquer ce résultat par mail (laurent.boucaud@polymtl.ca) et me joindre votre fichier de prédiction sur l'ensemble de test(pour vérification).

Une conversation dans le forum sera créée pour tenir à jour le meilleur score obtenu par une des équipes du cours.

Tant qu'aucun forum n'est créé, **ne m'envoyez pas vos performances si elles sont supérieures à 0.8 de log loss**.

Une fois le premier meilleur score affiché dans le forum, **ne me communiquez vos résultats que si votre log loss est inférieure au précédent meilleur score**.

Le nombre de points obtenus sera proportionnel au classement des équipes.

# 1. Softmax Regression (10 points)

Dans cette partie vous implémenterez **softmax regression** la variante de **logistic regression** qui permet d'effectuer de la classification pour un nombre de classe supérieur à 2.

Le code à compléter se trouve dans le fichier **SoftmaxClassifier.py**. 

**Pour cet exercice, la contrainte est d'utiliser uniquement la bibliothèque numpy**

## Encapsulation avec sklearn

La classe **SoftmaxClassifier** hérite des classes **BaseEstimator** et **ClassifierMixin** de **scikit-learn** ce qui nous permettra d'utiliser facilement avec notre classifier les outils fournis par scikit-learn dans la suite du TP.

Pour la compatibilité, le classifier implémente obligatoirement les méthodes:

* **fit**: responsable de l'entraînement du modèle
* **predict_proba**: permet de prédire la probabilité de chaque classe pour chaque exemple du dataset fourni.
* **predict**: permet de prédire la classe pour chaque exemple du dataset fourni.
* **score**: permet de quantifier l'écart entre les classes prédites et les classes réelles pour le dataset fourni


## Train/Test set:

Quand on veut tester les performances de l'apprentissage d'un algorithme de machine learning, on **ne le teste pas sur les données utilisées pour l'apprentissage**.

En effet, ce qui nous intéresse c'est que notre algorithme soit **capable de généraliser** ses prédictions à des données qu'il n'a **jamais vu**.

Pour illustrer, si on teste un algorithme sur les données d'entrainement, on teste sa capacité à **apprendre par coeur** le dataset et non à **généraliser**.

Par conséquent, quand on reçoit un nouveau dataset, la première chose à faire et de le **diviser en deux parties**: un ensemble d'**entraînement** (**70-80%** du dataset) et un ensemble de **test**(**20-30%** du dataset).

Tous les algorithmes de **traitement des données** et d'apprentissage devront être appris uniquement sur l'ensemble d'entraînement et appliqués ensuite sur l'ensemble de test.

Cela garantit l'absence de connaissances préalables de l'ensemble de test lors de l'entrainement.

## Gradient descent

La descente de gradient est un algorithme qui permet trouver la solution optimale d'un certains nombre de problèmes. Le principe est le suivant: on définit une **fonction de coût J**  qui caractérise le problème.
Cette fonction dépend d'un ensemble de **paramètres $\theta$ **. La descente de gradient cherche à **minimiser** la fonction de coût en **modifiant itérativement** les paramètres.

### Gradient

Le gradient de la fonction de coûts pour un $\theta$ donné, correspond à la direction dans laquelle il faut modifier $\theta$ pour réduire la valeur de la fonction de coût. 

La fonction de coût est minimale quand le gradient est nul.

Concrètement, on initialize $\theta$ aléatoirement, et on effectue à chaque itération un pas pour réduire la fonction de coût jusqu'à convergence de l'algorithme à un minimum.

### Learning rate

Le taux d'apprentissage correspond à la taille du pas que l'on va effectuer dans la direction du gradient.
Plus il est grand, plus la convergence est rapide mais il y a un risque que l'algorithme diverge.

Plus il est petit, plus la convergence est lente.

### Batch gradient descent

Il existe plusieurs algorithmes de descente de gradient. Nous utiliserons Batch gradient descent.

Dans cet algorithme, avant de mettre à jour $\theta$, on calcule les gradients sur l'ensemble des exemples d'entraînement.

### Epoch

Il s'agit d'un pas de la descente de gradient, soit une unique mise à jour de gradient.

### Bias/Variance tradeoff

Lorsqu'on entraine un algorithme de machine learning on cherche un équilibre entre **biais** et **variance**.

Un modèle avec un **biais fort**, est un modèle qui est **trop simple** pour la structure donnée considérée (modèle linéaire pour données quadratiques), cela limite la capacité du modèle à généraliser. On appelle aussi le biais **underfitting**.

Un modèle avec une **variance élevée** signifie qu'il est sensible aux petites variations dans les données d'entrainement, cela correspond à l'**overfitting**, c'est-à-dire que le modèle est trop proche de la structure de l'ensemble d'entrainement ce qui **limite sa capacité à généraliser**.

Un modèle avec un **biais important** aura une **mauvaise performance** sur l'ensemble d'**entraînement**.
Un modèle avec une **variance importante** aura une performance bien **moins bonne** sur l'ensemble de **test** que sur l'ensemble d'**entrainement**.


### One-hot-encoding

En machine learning pour représenter un vecteur de données catégoriques, on utilise le one-hot encoding.

Pour un vecteur comportant 5 exemples et 3 catégories différentes, on le représente sous forme d'une matrice de taille 5 par 3. Cette matrice est entièrement remplie de 0 sauf à l'indice correspondant au numéro de la classe pour chaque exemple.


Par exemple
$ y = \left(\begin{array}{cc} 
1 \\
1 \\
2 \\
3 \\
2 \\
\end{array}\right) $

devient:

$ yohe =  \left(\begin{array}{cc} 
1. & 0. & 0.\\
1. & 0. & 0.\\
0. & 1. & 0.\\
0. & 0. & 1.\\
0. & 1. & 0.\\
\end{array}\right) $


#### Question 1 (1 point)
Implémentez  la fonction  **_one_hot**  dans SoftmaxClassifier.py

In [2]:
from softmaxClassifier import *
y = np.array([1,1,2,3,2])
smc = SoftmaxClassifier()
smc._one_hot(y)

IndexError: index 3 is out of bounds for axis 0 with size 3

### Matrice de poids

Soit $ X_{m * n} $ la matrice d'exemple et $ \Theta _{n*K} $ la matrice de poids avec:

* **m** le nombre d'exemples
* **n** le nombre de features
* **k** le nombre de classes

Il est d'usage d'ajouter une colonne supplémentaire à X, cette colonne est remplie de 1. Pour prendre en compte ce changement, il faut rajouter une ligne à la matrice $\Theta$.

On obtient X_bias$_{m*(n+1)}$ et $ \Theta _{(n+1)*K} $


Intuitivement, à chaque classe K est associée une colonne de $\theta$.

On note $\theta_k$ le vecteur de dimension n+1 la colonne de poids associée à la prédiction de la classe k.

$\Theta$ = [$\theta_0$,$\theta_1$... $\theta_k$ ... $\theta_n$ ]

Ainsi $ z = x * \Theta $ donne un vecteur de dimension K qui correspond aux **logits** associés à x pour chacune des classes.

#### Question 2 (1 point)
Dans la fonction  **fit**  dans SoftmaxClassifier.py instanciez X_bias et initialisez $\Theta$ aléatoirement. (ligne 74)

In [3]:
X = np.random.randint(1,5,(3,4))


### Softmax

On veut convertir le vecteur de logits **z** obtenu dans la partie précédente, en un **vecteur de probabilité**.

Pour cela on définit la **fonction softmax**:

$$ \hat{p_x}^k = softmax(z)_k = \frac{exp(z_k)}{\sum_{\substack{1<j<K}} exp(z_j)} $$

Intuitivement, pour un logit de z, $z_k$, on prend l'exponentielle de cette valeur et on la divise par la somme des exponentielles de chaque logit du vecteur **z**. On obtient  $\hat{p_x}^k$ la probabilité que l'exemple **x** appartienne à la classe **k**.

On réitère l'opération pour chaque logit du vecteur **z**. 

On obtient ainsi un vecteur de probabilités $\hat{p_x}$ pour un exemple **x**. 

La division permet de rendre la somme des termes du vecteur $\hat{p_x}$ égale à 1 ce qui est indispensable dans le cadre des probabilités.

#### Question 3 (1 point)
Implémentez  la fonction  **_softmax**  dans SoftmaxClassifier.py

In [4]:
from softmaxClassifier import *
X = np.random.randint(0,5,(3,4))
print(X)
smc = SoftmaxClassifier()
smc._softmax(X)
smc._one_hot(X)

[[0 4 2 2]
 [4 0 1 3]
 [2 3 4 1]]
[[0 4 2 2]
 [4 0 1 3]
 [2 3 4 1]]
[[ 1.         54.59815003  7.3890561   7.3890561 ]
 [54.59815003  1.          2.71828183 20.08553692]
 [ 7.3890561  20.08553692 54.59815003  2.71828183]]


array([[[0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.]],

       [[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.]],

       [[0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.]]])

#### Question 4 (1 point)
En utilisant la fonction **_softmax** de la question 3, implémentez  les fonctions  **predict_proba** et **predict**  dans SoftmaxClassifier.py

### Fonction de coût Log loss

Soit la fonction de coût log loss (ou cross entropy):

$$ J( \Theta) = \frac{-1}{m}\sum_{\substack{1<i<m}} \sum_{\substack{1<k<K}} y_k^i log( \hat{p_k}^i ) $$

avec:
* **K** le nombre de classes
* **m** le nombre d'exemples dans les données
* $ \hat{p_k}^i  $  la probabilité que l'exemple i soit de la classe k
* $y_k^i$ vaut 1 si la classe cible de l'exemple i est k, 0 sinon

**Détail d'implémentation:** La fonction n'est pas définie pour des valeurs de probabilité de 0. ou 1., il faut donc s'assurer que étant donné $\epsilon$, les probabilités sont comprises dans [$\epsilon$, 1. - $\epsilon$].
#### Question 5 (1 point)
Implémentez  la fonction  **_cost_function**  dans SoftmaxClassifier.py en prenant en compte le **détail d'implémentation** (variable self.eps) et utilisez-la pour calculer la variable **loss** dans la fonction **fit** (ligne 84)

### Gradient de la fonction de coût

Le **gradient de J** par rapport à la classe k (par rapport à $\theta_k$) est :


$$ \Delta_{\theta_k}J( \Theta) = \frac{1}{m} \sum_{\substack{1<i<m}}( \hat{p_k}^i - y_k^i)x^i  $$

avec:
* **K** le nombre de classes
* **m** le nombre d'exemples dans les données
* $ \hat{p_k}^i  $  la probabilité que l'exemple i soit de la classe k
* $y_k^i$ vaut 1 si la classe cible de l'exemple i est k, 0 sinon

Sous **forme matricielle**, on peut écrire le **gradient de J par rapport à $\Theta$**:
$$ \Delta_J( \Theta) = \frac{1}{m} X_{bias}^T *( \hat{p} - y_{ohe}) $$

avec:
* $\hat{p}$ la matrice de probabilité prédite pour chaque example et pour chaque classe
* $y_{ohe}$ la version one-hot de y
* $X_{bias}^T$  la matrice transposée de $X_{bias}$
* **\*** le produit matriciel

#### Question 6 (1 point)
Implémentez  la fonction  **_get_gradient**  dans SoftmaxClassifier.py

### Mise à jour des poids

Quand le gradient a été calculé, il faut mettre à jour les poids avec ces gradients.

$$ \Theta  = \Theta - \gamma \Delta J( \Theta) $$


avec:
* $\Theta$ la matrice de poids
* $\gamma$  le taux d'apprentissage
* $\Delta J( \Theta)$ le gradient de $J( \Theta)$ selon $\Theta$

#### Question 7 (1 point)
Mettez à jour la variable **self.theta_** dans la fonction **fit**  dans SoftmaxClassifier.py (ligne 85)

### Regularization

Pour limiter l'**overfitting**, on utilise la régularisation, il s'agit d'ajouter un terme à la fonction de coût $J( \Theta)$.

Ce terme va ajouter des contraintes sur les poids du modèle lors de l'entrainement.
Nous allons utiliser la régularisation **L2** :

$$ L2(\Theta) = \alpha \sum_{\substack{1<=i<n}} \sum_{\substack{0<=k<K}} \theta_{i,k}^2 $$ 

avec:

* $\alpha$ le coefficient de régularisation

**Remarque:** La première somme ne commence pas à 0 mais à 1 parce qu'on ne régularise pas les poids associés à la colonne de biais de X.

Le fait d'ajouter ce terme conduit le modèle à apprendre les données tout en gardant ses poids le plus petit possible.



#### Question 8 (1 point)
Modifiez les fonctions  **_get_gradient** et **_cost_function** pour prendre en compte la régularisation lorsque le booléen self.regularization est vrai  dans SoftmaxClassifier.py

#### Question 9 (1 point)

Le terme de régularisation est utilisé uniquement pendant l'entraînement. Quand on veut évaluer la performance du modèle **après entrainement**, on utilise la fonction de coût **non-régulée**.

Implémentez la fonction **score** qui permet d'évaluer la qualité de la prédiction **après entrainement** dans SoftmaxClassifier.py

### Early stopping

Un trop grand nombre d'**epoch** peut résulter en **overfitting**.
Pour pallier à ce problème, on peut utiliser le mécanisme d'**early stopping**.
Il s'agit d'arrêter l'entraînement si la différence de la fonction de coût entre deux **epochs consécutives** est inférieure à un **seuil**.




#### Question 10 (1 point)

Finissez d'implémenter la fonction **fit** en y ajoutant le mécanisme d'**early stopping**  quand le booléen **self.early_stopping** est vrai le seuil est donné par la variable **self.threshold**.

## Test de la solution:

Le code ci-dessous importe le dataset de classification multiclasse **iris** disponible sur sklearn. Les données sont divisées en deux parties, l'ensemble d'entraînement et l'ensemble de test, puis elles sont normalisées.

Le classifier implémenté dans le fichier **SoftmaxClassifier.py** est importé puis entrainé sur l'ensemble d'entrainement et testé sur l'ensemble de test.

Le but de cette partie est juste de vérifier votre implémentation **quand vous êtes sûrs que votre code fonctionne**.

In [3]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# load dataset
data,target =load_iris().data,load_iris().target

# split data in train/test sets
X_train, X_test, y_train, y_test = train_test_split( data, target, test_size=0.33, random_state=42)

# standardize columns using normal distribution
# fit on X_train and not on X_test to avoid Data Leakage
s = StandardScaler()
X_train = s.fit_transform(X_train)
X_test = s.transform(X_test)

In [4]:
from softmaxClassifier import SoftmaxClassifier

# import the custom classifier
cl = SoftmaxClassifier(regularization=False)

# train on X_train and not on X_test to avoid overfitting
train_p = cl.fit_predict(X_train,y_train)
test_p = cl.predict(X_test)


[[ 0.05397559 -0.15278309  0.0988075 ]
 [ 0.51387021 -0.03043507 -0.48343514]
 [-0.23405526  0.17833763  0.05571763]
 [ 0.59768341 -0.07428313 -0.52340028]
 [ 0.57476397 -0.03682674 -0.53793723]]
[[ 0.04679694 -0.14013005  0.09333312]
 [ 0.47087537 -0.03021382 -0.44066155]
 [-0.21165027  0.17502831  0.03662196]
 [ 0.54805699 -0.07383239 -0.4742246 ]
 [ 0.52607197 -0.03665046 -0.48942151]]
[[ 0.04228922 -0.13014245  0.08785323]
 [ 0.42589033 -0.02942597 -0.39646436]
 [-0.1896906   0.17067062  0.01901997]
 [ 0.49687768 -0.07235201 -0.42452567]
 [ 0.47608868 -0.03556101 -0.44052766]]
[[ 0.03995263 -0.12282857  0.08287595]
 [ 0.38164412 -0.02821842 -0.3534257 ]
 [-0.16945155  0.16549306  0.00395849]
 [ 0.44709802 -0.0699985  -0.37709952]
 [ 0.42764643 -0.0336671  -0.39397933]]
[[ 0.03916442 -0.1178104   0.07864598]
 [ 0.3403164  -0.02677155 -0.31354485]
 [-0.15166691  0.15981788 -0.00815097]
 [ 0.40096607 -0.0670469  -0.33391917]
 [ 0.38287023 -0.03120159 -0.35166864]]
[[ 0.03934428 -0.114

[[ 0.01560002 -0.03936849  0.02376847]
 [ 0.01771026 -0.01342907 -0.00428119]
 [-0.01154622 -0.00222113  0.01376735]
 [ 0.02907436  0.0011661  -0.03024046]
 [ 0.02558619  0.01733027 -0.04291646]]
[[ 0.01549365 -0.03921175  0.0237181 ]
 [ 0.01762303 -0.01341028 -0.00421275]
 [-0.01147488 -0.00234234  0.01381722]
 [ 0.02894498  0.00119813 -0.03014312]
 [ 0.025471    0.01729768 -0.04276868]]
[[ 0.01538853 -0.03905695  0.02366842]
 [ 0.0175369  -0.01339105 -0.00414586]
 [-0.01140475 -0.00246072  0.01386547]
 [ 0.02881727  0.00122957 -0.03004684]
 [ 0.02535733  0.01726489 -0.04262222]]
[[ 0.01528463 -0.03890404  0.02361941]
 [ 0.01745187 -0.01337138 -0.00408049]
 [-0.0113358  -0.00257633  0.01391213]
 [ 0.02869117  0.00126044 -0.0299516 ]
 [ 0.02524517  0.01723189 -0.04247706]]
[[ 0.01518194 -0.03875299  0.02357105]
 [ 0.0173679  -0.0133513  -0.0040166 ]
 [-0.011268   -0.00268924  0.01395724]
 [ 0.02856665  0.00129074 -0.02985739]
 [ 0.02513447  0.01719871 -0.04233318]]
[[ 0.01508043 -0.038

 [ 0.01763351  0.01327341 -0.03090692]]
[[ 0.00806741 -0.02783856  0.01977115]
 [ 0.01151593 -0.00997198 -0.00154396]
 [-0.00741835 -0.00663585  0.0140542 ]
 [ 0.01992083  0.00287993 -0.02280076]
 [ 0.01759395  0.01324301 -0.03083696]]
[[ 0.0080313  -0.02777636  0.01974506]
 [ 0.01148491 -0.00994354 -0.00154137]
 [-0.00740261 -0.00663364  0.01403625]
 [ 0.0198749   0.0028849  -0.0227598 ]
 [ 0.01755462  0.0132127  -0.03076731]]
[[ 0.00799544 -0.02771445  0.01971901]
 [ 0.01145408 -0.00991518 -0.00153889]
 [-0.007387   -0.0066312   0.01401821]
 [ 0.01982925  0.00288979 -0.02271904]
 [ 0.01751552  0.01318246 -0.03069799]]
[[ 0.00795983 -0.02765284  0.01969301]
 [ 0.01142343 -0.00988691 -0.00153651]
 [-0.00737153 -0.00662854  0.01400007]
 [ 0.01978386  0.00289461 -0.02267847]
 [ 0.01747666  0.01315231 -0.03062898]]
[[ 0.00792446 -0.02759152  0.01966706]
 [ 0.01139296 -0.00985873 -0.00153423]
 [-0.00735619 -0.00662566  0.01398185]
 [ 0.01973874  0.00289935 -0.02263809]
 [ 0.01743803  0.013

[[ 0.00502968 -0.02199219  0.01696262]
 [ 0.00876853 -0.00722912 -0.00153946]
 [-0.00613426 -0.00559712  0.01173166]
 [ 0.01580146  0.00312176 -0.01892338]
 [ 0.01408055  0.01019767 -0.02427837]]
[[ 0.0050119  -0.02195318  0.0169414 ]
 [ 0.00875126 -0.00721131 -0.00153999]
 [-0.00612655 -0.00558604  0.01171288]
 [ 0.01577507  0.00312195 -0.01889718]
 [ 0.01405806  0.01017655 -0.02423477]]
[[ 0.00499421 -0.02191431  0.01692021]
 [ 0.00873405 -0.00719358 -0.00154052]
 [-0.00611887 -0.00557497  0.01169414]
 [ 0.01574877  0.00312212 -0.01887106]
 [ 0.01403566  0.01015551 -0.02419133]]
[[ 0.00497662 -0.02187556  0.01689907]
 [ 0.00871691 -0.00717593 -0.00154104]
 [-0.00611122 -0.0055639   0.01167542]
 [ 0.01572257  0.00312227 -0.01884501]
 [ 0.01401334  0.01013453 -0.02414804]]
[[ 0.00495911 -0.02183695  0.01687796]
 [ 0.00869985 -0.00715835 -0.00154156]
 [-0.0061036  -0.00555283  0.01165674]
 [ 0.01569647  0.0031224  -0.01881905]
 [ 0.0139911   0.01011362 -0.02410489]]
[[ 0.0049417  -0.021

 [ 0.01168588  0.00793011 -0.01961764]]
[[ 0.00329675 -0.01777785  0.01448268]
 [ 0.00695797 -0.00542965 -0.00152929]
 [-0.00530502 -0.00425573  0.00956237]
 [ 0.0129821   0.00305396 -0.01603773]
 [ 0.01167094  0.00791611 -0.01958872]]
[[ 0.00328722 -0.01775185  0.01446623]
 [ 0.00694706 -0.00541944 -0.00152861]
 [-0.00529978 -0.0042469   0.00954831]
 [ 0.01296476  0.00305305 -0.01601949]
 [ 0.01165604  0.00790215 -0.01955987]]
[[ 0.00327772 -0.01772592  0.01444981]
 [ 0.00693619 -0.00540927 -0.00152791]
 [-0.00529455 -0.00423809  0.00953427]
 [ 0.01294745  0.00305214 -0.0160013 ]
 [ 0.01164118  0.00788824 -0.01953111]]
[[ 0.00326827 -0.01770007  0.01443342]
 [ 0.00692536 -0.00539915 -0.00152721]
 [-0.00528933 -0.0042293   0.00952027]
 [ 0.0129302   0.00305123 -0.01598315]
 [ 0.01162636  0.00787437 -0.01950244]]
[[ 0.00325885 -0.01767428  0.01441706]
 [ 0.00691455 -0.00538906 -0.00152651]
 [-0.00528412 -0.00422053  0.0095063 ]
 [ 0.01291299  0.00305031 -0.01596504]
 [ 0.01161158  0.007

 [ 0.00975931  0.00618159 -0.01594387]]
[[ 0.0021945  -0.01447454  0.01228284]
 [ 0.00558704 -0.00422846 -0.00136046]
 [-0.00460093 -0.00312828  0.00773163]
 [ 0.01075703  0.00289946 -0.01365947]
 [ 0.00974896  0.00617258 -0.01592452]]
[[ 0.00218927 -0.01445716  0.01227069]
 [ 0.00557989 -0.00422264 -0.00135912]
 [-0.00459696 -0.00312241  0.0077218 ]
 [ 0.01074516  0.00289845 -0.01364659]
 [ 0.00973864  0.00616359 -0.01590522]]
[[ 0.00218406 -0.01443983  0.01225856]
 [ 0.00557275 -0.00421684 -0.00135778]
 [-0.00459301 -0.00311656  0.00771199]
 [ 0.01073332  0.00289744 -0.01363374]
 [ 0.00972834  0.00615463 -0.01588596]]
[[ 0.00217887 -0.01442253  0.01224646]
 [ 0.00556562 -0.00421106 -0.00135644]
 [-0.00458905 -0.00311072  0.0077022 ]
 [ 0.0107215   0.00289642 -0.01362091]
 [ 0.00971807  0.00614569 -0.01586675]]
[[ 0.0021737  -0.01440527  0.01223438]
 [ 0.00555852 -0.0042053  -0.0013551 ]
 [-0.00458511 -0.0031049   0.00769244]
 [ 0.0107097   0.00289541 -0.01360811]
 [ 0.00970781  0.006

[[ 0.001633   -0.01248025  0.01085052]
 [ 0.00476817 -0.00359287 -0.00117724]
 [-0.00412228 -0.00246797  0.00659289]
 [ 0.00937866  0.00276976 -0.01215162]
 [ 0.0085454   0.00515671 -0.01370528]]
[[ 0.00162962 -0.01246735  0.01084101]
 [ 0.0047629  -0.00358896 -0.00117587]
 [-0.00411901 -0.0024638   0.00658546]
 [ 0.00936964  0.00276883 -0.01214166]
 [ 0.00853748  0.00515025 -0.0136909 ]]
[[ 0.00162625 -0.01245449  0.01083152]
 [ 0.00475763 -0.00358506 -0.0011745 ]
 [-0.00411575 -0.00245965  0.00657805]
 [ 0.00936063  0.0027679  -0.01213172]
 [ 0.00852958  0.0051438  -0.01367654]]
[[ 0.00162289 -0.01244164  0.01082204]
 [ 0.00475237 -0.00358117 -0.00117313]
 [-0.00411249 -0.00245551  0.00657065]
 [ 0.00935163  0.00276697 -0.0121218 ]
 [ 0.00852169  0.00513736 -0.01366222]]
[[ 0.00161954 -0.01242883  0.01081258]
 [ 0.00474713 -0.00357729 -0.00117176]
 [-0.00410923 -0.00245137  0.00656326]
 [ 0.00934266  0.00276604 -0.01211189]
 [ 0.00851382  0.00513094 -0.01364792]]
[[ 0.0016162  -0.012

[[ 0.00125027 -0.0109352   0.00968864]
 [ 0.00413712 -0.00314049 -0.00099828]
 [-0.00371305 -0.00198201  0.00569789]
 [ 0.00828525  0.00264855 -0.01093678]
 [ 0.00758263  0.00439247 -0.01197801]]
[[ 0.00124798 -0.01092537  0.0096811 ]
 [ 0.00413311 -0.00313771 -0.00099705]
 [-0.00371032 -0.001979    0.00569216]
 [ 0.00827821  0.00264771 -0.0109289 ]
 [ 0.00757641  0.00438767 -0.01196699]]
[[ 0.00124569 -0.01091555  0.00967357]
 [ 0.00412911 -0.00313493 -0.00099583]
 [-0.0037076  -0.00197601  0.00568644]
 [ 0.00827118  0.00264687 -0.01092103]
 [ 0.00757019  0.00438288 -0.01195598]]
[[ 0.00124341 -0.01090575  0.00966606]
 [ 0.00412511 -0.00313216 -0.00099461]
 [-0.00370488 -0.00197302  0.00568074]
 [ 0.00826416  0.00264603 -0.01091318]
 [ 0.00756399  0.0043781  -0.011945  ]]
[[ 0.00124113 -0.01089596  0.00965855]
 [ 0.00412113 -0.0031294  -0.00099338]
 [-0.00370216 -0.00197004  0.00567504]
 [ 0.00825715  0.00264519 -0.01090533]
 [ 0.00755779  0.00437333 -0.01193403]]
[[ 0.00123887 -0.010

In [5]:
test_p

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)

In [6]:
y_test-test_p

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0], dtype=int64)

In [12]:
y_train-train_p

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       -1,  0,  0,  0,  0, -1,  0,  0, -1,  1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int64)

Si vous obtenez des valeurs relativement proches pour l'ensemble de test et d'entrainement, et qu'elles sont au moins supérieures à 0.8, votre modèle devrait être correct

In [7]:
from sklearn.metrics import precision_recall_fscore_support

# display precision, recall and f1-score on train/test set
print("train : "+ str(precision_recall_fscore_support(y_train, train_p,average = "macro")))
print("test : "+ str(precision_recall_fscore_support(y_test, test_p,average = "macro")))

train : (0.9729729729729729, 0.9714285714285714, 0.9709901198234182, None)
test : (0.9791666666666666, 0.9791666666666666, 0.978494623655914, None)


In [14]:
# import matplotlib.pyplot as plt

# plt.plot(cl.losses_)
# plt.show()

# 2. Data preprocessing (8 points)

##  Kaggle 
Kaggle est un site dédié au machine learning. On y retrouve un grand nombre de dataset.
Des compétitions sont organisées par des organisations. Ces dernières fournissent un dataset et un objectif. Les "kagglers" qui participent à ces compétitions soumettent leurs résultats en ligne. Il y a souvent des prix ou des emplois pour ceux qui obtiennent les meilleurs résultats.

Il s'agit d'un bon moyen pour développer ses compétences en machine learning sur des vrais datasets.

Vous pouvez créer un compte si vous voulez comparer vos résultats à ceux déjà en ligne pour la dataset que nous allons étudier.

Vous pouvez créer un compte ici: https://www.kaggle.com/


## Austin Animal Center Shelter Animal Outcomes dataset
Le dataset que nous utiliserons est le "Animal Outcomes dataset" disponible à l'adresse suivante: https://www.kaggle.com/c/shelter-animal-outcomes.

Il s'agit d'un problème de **classification multiclasse** des animaux sont recueillis dans un refuge après avoir été abandonnés, le but est de prédire la manière dont ils vont "quitter " le lieu:
* Adoption
* Retour au propriétaire
* Décès 
* Euthanasie
* Transfert à un autre centre

Pour plus d'informations sur les données, rendez-vous sur kaggle.

## Déroulement d'un projet de machine learning

Le but de la suite de ce TP est de vous faire étudier une version simplifiée d'un projet complet de machine learning:

1. Nettoyage des données, traitement des valeurs manquantes
2. Mise en forme des données pour pouvoir les utiliser dans les algorithmes de machine learning
3. Feature engineering: transformation ou combinaison de features entre elles
4. Comparaison des performances des différents choix effectués lors du traîtement des données
5. Comparaison des performances de différents modèles (dont celui implémenté en première partie)
6. Optimisation des hyper-paramètres

## Scikit-learn
http://scikit-learn.org/stable/

Il s'agit d'une bibliothèque de machine learning et data mining, elle propose des outils pour l'analyse et le traîtement des données,  des algorithmes classiques de machine learning comme les réseaux de neuronnes, la régression logistique, les SVM ou autre, enfin des outils permettant de comparer les modèles entre eux comme la cross validation.

## Pandas

Une bibliothèque permettant de stocker des données et de les manipuler facilement

Les deux éléments de base de pandas sont le dataframe et la serie.

https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.html

## Data processing tutorial

**Avant de continuer le TP**, familiarisez-vous avec le **pré-traitement des données**, **pandas** et **scikit-learn**, un tutoriel est disponible dans le fichier: **data_processing_tutorial.ipynb**

## Dataset

#### Chargement de l'ensemble d'entraînement et de l'ensemble de test

In [8]:
import pandas as pd

PATH = "data/"
X_train = pd.read_csv(PATH + "train.csv")
X_test = pd.read_csv(PATH + "test.csv")

#### Suppression de colonnes inutiles

In [2]:
X_train = X_train.drop(columns = ["OutcomeSubtype","AnimalID"])
X_test = X_test.drop(columns = ["ID"])

In [3]:
X_train, y_train = X_train.drop(columns = ["OutcomeType"]),X_train["OutcomeType"]

#### 5 premiers exemples de l'ensemble d'entraînement

In [250]:
X_train.head()

Name             DateTime AnimalType SexuponOutcome AgeuponOutcome  \
0  Hambone  2014-02-12 18:22:00        Dog  Neutered Male         1 year   
1    Emily  2013-10-13 12:44:00        Cat  Spayed Female         1 year   
2   Pearce  2015-01-31 12:28:00        Dog  Neutered Male        2 years   
3      NaN  2014-07-11 19:09:00        Cat    Intact Male        3 weeks   
4      NaN  2013-11-15 12:52:00        Dog  Neutered Male        2 years   

                         Breed        Color  
0        Shetland Sheepdog Mix  Brown/White  
1       Domestic Shorthair Mix  Cream Tabby  
2                 Pit Bull Mix   Blue/White  
3       Domestic Shorthair Mix   Blue Cream  
4  Lhasa Apso/Miniature Poodle          Tan

#### 5 premiers exemples de l'ensemble de test

In [226]:
X_test.head()

Name             DateTime AnimalType SexuponOutcome AgeuponOutcome  \
0    Summer  2015-10-12 12:15:00        Dog  Intact Female      10 months   
1  Cheyenne  2014-07-26 17:59:00        Dog  Spayed Female        2 years   
2       Gus  2016-01-13 12:20:00        Cat  Neutered Male         1 year   
3     Pongo  2013-12-28 18:12:00        Dog    Intact Male       4 months   
4   Skooter  2015-09-24 17:59:00        Dog  Neutered Male        2 years   

                            Breed        Color  
0          Labrador Retriever Mix    Red/White  
1  German Shepherd/Siberian Husky    Black/Tan  
2          Domestic Shorthair Mix  Brown Tabby  
3               Collie Smooth Mix     Tricolor  
4            Miniature Poodle Mix        White

#### 5 premiers exemples de l'attribut à prédire

In [232]:
y_train.head()

0    Return_to_owner
1         Euthanasia
2           Adoption
3           Transfer
4           Transfer
Name: OutcomeType, dtype: object

## Travail demandé

Pour vous faire gagner du temps, une partie des colonnes (Name,DateTime,color) ont déjà été traitées.


En vous appuyant sur le tutoriel fourni, vous devez écrire un pipeline complet de transformation pour chacune des colonnes restantes du dataset (AgeuponOutcome,AnimalType,SexuponOutcome, Breed).

Vous êtes **libres** de vos choix, mais vous devez les **justifer** colonne par colonne.
Par exemple, vous pouvez choisir de combiner des colonnes entre elles, de séparer une colonne en plusieurs ou encore d'éliminer complètement une colonne si vous le justifiez correctement.


La partie déjà prétraitée du dataset est chargée dans **X_train1** et **X_test1**

In [234]:
X_train1 = pd.read_csv("data/train_preprocessed.csv")
X_test1 = pd.read_csv("data/test_preprocessed.csv")

In [235]:
X_train1.head()

Color  HasName  Month  Day  Hour
0  0.973624      1.0    2.0  1.0   3.0
1 -1.421532      1.0   10.0  1.0   2.0
2  0.973624      1.0    1.0  3.0   2.0
3 -1.471381      0.0    7.0  1.0   3.0
4 -0.868974      0.0   11.0  1.0   2.0

Le reste du dataset que vous devez traiter est:

In [236]:
X_train = X_train.drop(columns = ["Color","Name","DateTime"])
X_test = X_test.drop(columns = ["Color","Name","DateTime"])

In [237]:
X_train.head()

AnimalType SexuponOutcome AgeuponOutcome                        Breed
0        Dog  Neutered Male         1 year        Shetland Sheepdog Mix
1        Cat  Spayed Female         1 year       Domestic Shorthair Mix
2        Dog  Neutered Male        2 years                 Pit Bull Mix
3        Cat    Intact Male        3 weeks       Domestic Shorthair Mix
4        Dog  Neutered Male        2 years  Lhasa Apso/Miniature Poodle

####  Question 11: AgeuponOutcome (1 point)

...

#### Question 12: AnimalType (1 point)

...

#### Question 13: SexuponOutcome (1 point)

...

#### Question 14: Breed (1 point)

...

### Pipeline
**Question 15: Complétez pipeline ci-dessous (4 points)**

In [ ]:
from preprocessing import TransformationWrapper
from preprocessing import LabelEncoderP
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.compose import ColumnTransformer

# pipeline_color = Pipeline([
#     ("name", Transformer()),
# ])


# full_pipeline = ColumnTransformer([
#         ("color", pipeline_color, ["Color"]),
        

#     ])

Lancez le pipeline

In [ ]:
# column_names = []
# X_train_prepared = pd.DataFrame(full_pipeline.fit_transform(X_train),columns = columns)
# X_test_prepared = pd.DataFrame(full_pipeline.fit_transform(X_test),columns = columns)

#### Concaténation des deux parties du dataset:

In [ ]:
# X_train = pd.concat([X_train1,X_train_prepared], axis = 1)
# X_test = pd.concat([X_test1,X_test_prepared], axis = 1)

# 3. Model selection (2 points)

Encodage de la classe cible sous forme d'entiers pour l'utiliser
avec les algorithmes de scikit-learn

In [5]:
from sklearn.preprocessing import LabelEncoder
target_label = LabelEncoder()
y_train_label = target_label.fit_transform(y_train)
print(target_label.classes_)

['Adoption' 'Died' 'Euthanasia' 'Return_to_owner' 'Transfer']


## Ensemble de validation
Pour comparer différents modèles entre eux, on ne peut pas utiliser
l'ensemble de test, sinon on serait tenté de garder le modèle correspondant le mieux à l'ensemble de test ce qui pourrait conduire à l'overfitting.

Il est d'usage de créer un nouvel ensemble de la taille de l'ensemble de test, l'ensemble de **validation**.


## Cross-validation

La cross-validation est une méthode utile pour comparer la performance de différents modèles de machine learning **sans créer d'ensemble de validation**.

Il existe différents types de cross-validation, la procédure la plus classique est la suivante:
* Diviser aléatoirement l'ensemble d'entraînement en deux parties (90%/10% par exemple).
* Entraîner le modèle sur la plus grande partie, et le tester sur l'autre partie.
* Recommencer n fois
* Calculer la moyenne et l'écart type des résultats

Les avantages sont les suivants:
* Considérer la totalité de l'ensemble d'entraînement pour l'évaluation (sans se priver de l'ensemble de validation)
* Obtenir l'écart-type des résultats permet une meilleure évaluation de la précision du modèle.

L'inconvénient principal est le temps de calcul, étant donné que l'on effectue l'apprentissage du modèle plusieurs fois, cette méthode peut être impossible pour des datasets contenant un grand nombre d'exemple (> 10e5)



## Bonus 2: StratifiedKFold (1 point)

En observant la distribution des classes de l'attribut cible (à l'aide des fonctions de visualisation de pandas), justifiez l'utilisation de l'objet **StratifiedKFold** de sklearn pour la division de l'ensemble d'entraînement lors de cross-validation en comparaison à une méthode pûrement **aléatoire**.

## Question 16: (1 point)


**Choisir au moins deux modèles permettant la classification multiclasse sur sklearn en plus du modèle implémenté dans la première partie du TP**.

**Complétez la fonction compare qui effectue la crossvalidation pour différents modèles et différentes métriques, et renvoie la liste des moyennes et écart-types pour chacune des métriques, pour chacun des modèles. **

**En vous basant sur les différentes métriques, concluez quant au modèle le plus performant.**

Evaluez les modèles pour les différentes métriques proposées:
* **log loss**: c'est la métrique d'évaluation de kaggle
* **precision**: correspond à la qualité de la prédiction, le nombre de classes correctement prédites par le nombre de prédiction total
* **recall**: le nombre d'éléments appartenant à une classe, identifiés comme tel, divisé par le nombre total des éléments de cette classe.
* **f-score**: une moyenne de la precision et du recall

**Remarque: precision et recall sont deux mesures complémentaires pour l'évaluation d'un modèle de classification multi-classe.**

Dans le cas d'une classification binaire avec un déséquilibre de la classe cible important, (90%/10%), en évaluant le résultat de la classification avec l'accuracy (nombre de prédictions correctes divisé par le nombre de prédictions total), on peut obtenir un très bon score (90% d'accuracy) en choisissant de prédire systématiquement la classe majoritaire.

Dans un tel cas, la precision serait élevée de même, mais le recall serait très bas , nous indiquant la médiocrité de notre modèle.


In [255]:
def compare(models,X_train,y_train,nb_runs):
    losses = []
    
    return losses

In [ ]:
from SoftmaxClassifier import SoftmaxClassifier

nb_run = 3

models = [
    SoftmaxClassifier(),
]

scoring = ['neg_log_loss', 'precision_macro','recall_macro','f1_macro']

compare(models,X_train,y_train_label,nb_run,scoring)

...

## Question 17: Matrice de confusion (0.5 point)

La matrice de confusion A est telle que $A_{i,j}$ correspond au nombre d'exemples de la classe i classifié comme appartenant à la classe j.

Entrainez le modèle sélectionné sur la totalité de l'ensemble d'entraînement.
A l'aide de la matrice de confusion et de la distribution des classes, analysez plus en détail les performances du modèle choisi et justifiez les.

In [26]:
# Train selected model

selected_model = 
y_pred = selected_model.fit_predict(X_train,y_train_label)

###### Matrice de confusion

In [ ]:
from sklearn.metrics import confusion_matrix
pd.DataFrame(confusion_matrix(y_train_label, y_pred), columns = target_label.classes_, index = target_label.classes_)

###### Distribution des classes

In [ ]:
import matplotlib.pyplot as plt 
print(target_label.classes_)
pd.Series(y_train_label).hist()

## Bonus 3: Optimisation des hyper-paramètres (1 point)

Les hyper-paramètres sont les paramètres fixés avant la phase d'apprentissage. Pour optimiser les performances du modèle, on peut sélectionner les meilleurs hyper-paramètres.

A l'aide de sklearn, optimisez les hyper-paramètres du modèle que vous avez sélectionné et montrez que les performances ont été améliorées.
Vous pouvez utiliser par exemple: **GridSearchCV**


## Question 18: Soumission (0.5 point)

Enfin, effectuez la prédiction sur l'ensemble de test et joignez vos résultats au rendu du TP.

**Optionnel**: Vous pouvez soumettre vos résultats sur kaggle et noter votre performance en terme de log loss.

In [ ]:
# best_model = 
# pred_test = pd.Series(best_model.transform(X_test))
# pred_test.to_csv("test_prediction.csv",index = False)